---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/nqqwzomy/public_html/amirhamzadev
    - npm install --prefix $DEPLOYPATH
    - npm run build --prefix $DEPLOYPATH
    - rsync -a $DEPLOYPATH/build/ $DEPLOYPATH